### ISSUE TITLE
Peer to Peer Code Review 2

### ISSUE THREAD

**Issue by PromzzyKoncepts** [NgozikaNwocha/AwesomeBooks#3]
@NgozikaNwocha @John-Kibirige 
# Good Job 🤝 
> Great Job at completing the work and meeting up to the project requirements,
here are some issue I found with your project

- Your Readme file seems to be missing some important details like author names and their respective profile links
- You are required to use a MIT.md file with your details properly edited, kindly add the file in your project, or remove the link to the MIT licensing if you choose to omit that part out
- You should use more of classes to write your javascript code as required in the project, so use this [code](https://github.com/PromzzyKoncepts/BookStore/blob/134df6eee72bb4f60316659065b5430753b724fe/app.js#L1 ) to disable the max classes per file rule 
## Great Work Guys

**Comment by John-Kibirige** [comment]
Thank you @PromzzyKoncepts  for your wonderful review, we will surely make these corrections
